[package]
name = "subs-text"
description = "In-container text subtitle decoders: mov_text (3GPP Timed Text), USF, CMML, Kate"
version.workspace = true
edition.workspace = true
license = "LGPL-2.1-or-later"
publish.workspace = true

[dependencies]
oxideav-core.workspace = true

[dev-dependencies]
codecs = { path = "../codecs" }
refcheck.workspace = true
oxideav-mkv.workspace = true
oxideav-mp4.workspace = true
oxideav-ogg.workspace = true
oxideav-subtitle.workspace = true
oxideav-ass.workspace = true
