[package]
name = "codec-rv"
description = "RealVideo 1.0, 2.0, 3.0, 4.0 (RV10, RV20, RV30, RV40) decoders"
version.workspace = true
edition.workspace = true
license = "LGPL-2.1-or-later"
publish.workspace = true

[dependencies]
oxideav-core.workspace = true

[dev-dependencies]
refcheck.workspace = true
oxideav-mkv.workspace = true
demux-rm = { path = "../demux-rm" }
