// Ported from FFmpeg libavcodec/mlp.c, libavcodec/mlp_parse.c, libavcodec/mlpdec.c (commit 2da55bf).
// Licensed under LGPL-2.1-or-later.

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct VlcEntry {
    pub sym: u8,
    pub bits: u8,
}

pub const HUFF_LUT_0: [VlcEntry; 512] = [
    VlcEntry { sym: 0, bits: 0 }, VlcEntry { sym: 0, bits: 9 }, VlcEntry { sym: 1, bits: 8 }, VlcEntry { sym: 1, bits: 8 }, VlcEntry { sym: 2, bits: 7 }, VlcEntry { sym: 2, bits: 7 }, VlcEntry { sym: 2, bits: 7 }, VlcEntry { sym: 2, bits: 7 },
    VlcEntry { sym: 3, bits: 6 }, VlcEntry { sym: 3, bits: 6 }, VlcEntry { sym: 3, bits: 6 }, VlcEntry { sym: 3, bits: 6 }, VlcEntry { sym: 3, bits: 6 }, VlcEntry { sym: 3, bits: 6 }, VlcEntry { sym: 3, bits: 6 }, VlcEntry { sym: 3, bits: 6 },
    VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 },
    VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 },
    VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 },
    VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 },
    VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 },
    VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 },
    VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 },
    VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 },
    VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 },
    VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 },
    VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 },
    VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 },
    VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 },
    VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 },
    VlcEntry { sym: 0, bits: 0 }, VlcEntry { sym: 17, bits: 9 }, VlcEntry { sym: 16, bits: 8 }, VlcEntry { sym: 16, bits: 8 }, VlcEntry { sym: 15, bits: 7 }, VlcEntry { sym: 15, bits: 7 }, VlcEntry { sym: 15, bits: 7 }, VlcEntry { sym: 15, bits: 7 },
    VlcEntry { sym: 14, bits: 6 }, VlcEntry { sym: 14, bits: 6 }, VlcEntry { sym: 14, bits: 6 }, VlcEntry { sym: 14, bits: 6 }, VlcEntry { sym: 14, bits: 6 }, VlcEntry { sym: 14, bits: 6 }, VlcEntry { sym: 14, bits: 6 }, VlcEntry { sym: 14, bits: 6 },
    VlcEntry { sym: 13, bits: 5 }, VlcEntry { sym: 13, bits: 5 }, VlcEntry { sym: 13, bits: 5 }, VlcEntry { sym: 13, bits: 5 }, VlcEntry { sym: 13, bits: 5 }, VlcEntry { sym: 13, bits: 5 }, VlcEntry { sym: 13, bits: 5 }, VlcEntry { sym: 13, bits: 5 },
    VlcEntry { sym: 13, bits: 5 }, VlcEntry { sym: 13, bits: 5 }, VlcEntry { sym: 13, bits: 5 }, VlcEntry { sym: 13, bits: 5 }, VlcEntry { sym: 13, bits: 5 }, VlcEntry { sym: 13, bits: 5 }, VlcEntry { sym: 13, bits: 5 }, VlcEntry { sym: 13, bits: 5 },
    VlcEntry { sym: 12, bits: 4 }, VlcEntry { sym: 12, bits: 4 }, VlcEntry { sym: 12, bits: 4 }, VlcEntry { sym: 12, bits: 4 }, VlcEntry { sym: 12, bits: 4 }, VlcEntry { sym: 12, bits: 4 }, VlcEntry { sym: 12, bits: 4 }, VlcEntry { sym: 12, bits: 4 },
    VlcEntry { sym: 12, bits: 4 }, VlcEntry { sym: 12, bits: 4 }, VlcEntry { sym: 12, bits: 4 }, VlcEntry { sym: 12, bits: 4 }, VlcEntry { sym: 12, bits: 4 }, VlcEntry { sym: 12, bits: 4 }, VlcEntry { sym: 12, bits: 4 }, VlcEntry { sym: 12, bits: 4 },
    VlcEntry { sym: 12, bits: 4 }, VlcEntry { sym: 12, bits: 4 }, VlcEntry { sym: 12, bits: 4 }, VlcEntry { sym: 12, bits: 4 }, VlcEntry { sym: 12, bits: 4 }, VlcEntry { sym: 12, bits: 4 }, VlcEntry { sym: 12, bits: 4 }, VlcEntry { sym: 12, bits: 4 },
    VlcEntry { sym: 12, bits: 4 }, VlcEntry { sym: 12, bits: 4 }, VlcEntry { sym: 12, bits: 4 }, VlcEntry { sym: 12, bits: 4 }, VlcEntry { sym: 12, bits: 4 }, VlcEntry { sym: 12, bits: 4 }, VlcEntry { sym: 12, bits: 4 }, VlcEntry { sym: 12, bits: 4 },
    VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 },
    VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 },
    VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 },
    VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 },
    VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 },
    VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 },
    VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 },
    VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 }, VlcEntry { sym: 11, bits: 3 },
    VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 },
    VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 },
    VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 },
    VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 },
    VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 },
    VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 },
    VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 },
    VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 }, VlcEntry { sym: 7, bits: 3 },
    VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 },
    VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 },
    VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 },
    VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 },
    VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 },
    VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 },
    VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 },
    VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 },
    VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 },
    VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 },
    VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 },
    VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 },
    VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 },
    VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 },
    VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 },
    VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 },
    VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 },
    VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 },
    VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 },
    VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 },
    VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 },
    VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 },
    VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 },
    VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 }, VlcEntry { sym: 10, bits: 3 },
];

pub const HUFF_LUT_1: [VlcEntry; 512] = [
    VlcEntry { sym: 0, bits: 0 }, VlcEntry { sym: 0, bits: 9 }, VlcEntry { sym: 1, bits: 8 }, VlcEntry { sym: 1, bits: 8 }, VlcEntry { sym: 2, bits: 7 }, VlcEntry { sym: 2, bits: 7 }, VlcEntry { sym: 2, bits: 7 }, VlcEntry { sym: 2, bits: 7 },
    VlcEntry { sym: 3, bits: 6 }, VlcEntry { sym: 3, bits: 6 }, VlcEntry { sym: 3, bits: 6 }, VlcEntry { sym: 3, bits: 6 }, VlcEntry { sym: 3, bits: 6 }, VlcEntry { sym: 3, bits: 6 }, VlcEntry { sym: 3, bits: 6 }, VlcEntry { sym: 3, bits: 6 },
    VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 },
    VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 },
    VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 },
    VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 },
    VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 },
    VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 },
    VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 },
    VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 },
    VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 },
    VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 },
    VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 },
    VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 },
    VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 },
    VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 },
    VlcEntry { sym: 0, bits: 0 }, VlcEntry { sym: 15, bits: 9 }, VlcEntry { sym: 14, bits: 8 }, VlcEntry { sym: 14, bits: 8 }, VlcEntry { sym: 13, bits: 7 }, VlcEntry { sym: 13, bits: 7 }, VlcEntry { sym: 13, bits: 7 }, VlcEntry { sym: 13, bits: 7 },
    VlcEntry { sym: 12, bits: 6 }, VlcEntry { sym: 12, bits: 6 }, VlcEntry { sym: 12, bits: 6 }, VlcEntry { sym: 12, bits: 6 }, VlcEntry { sym: 12, bits: 6 }, VlcEntry { sym: 12, bits: 6 }, VlcEntry { sym: 12, bits: 6 }, VlcEntry { sym: 12, bits: 6 },
    VlcEntry { sym: 11, bits: 5 }, VlcEntry { sym: 11, bits: 5 }, VlcEntry { sym: 11, bits: 5 }, VlcEntry { sym: 11, bits: 5 }, VlcEntry { sym: 11, bits: 5 }, VlcEntry { sym: 11, bits: 5 }, VlcEntry { sym: 11, bits: 5 }, VlcEntry { sym: 11, bits: 5 },
    VlcEntry { sym: 11, bits: 5 }, VlcEntry { sym: 11, bits: 5 }, VlcEntry { sym: 11, bits: 5 }, VlcEntry { sym: 11, bits: 5 }, VlcEntry { sym: 11, bits: 5 }, VlcEntry { sym: 11, bits: 5 }, VlcEntry { sym: 11, bits: 5 }, VlcEntry { sym: 11, bits: 5 },
    VlcEntry { sym: 10, bits: 4 }, VlcEntry { sym: 10, bits: 4 }, VlcEntry { sym: 10, bits: 4 }, VlcEntry { sym: 10, bits: 4 }, VlcEntry { sym: 10, bits: 4 }, VlcEntry { sym: 10, bits: 4 }, VlcEntry { sym: 10, bits: 4 }, VlcEntry { sym: 10, bits: 4 },
    VlcEntry { sym: 10, bits: 4 }, VlcEntry { sym: 10, bits: 4 }, VlcEntry { sym: 10, bits: 4 }, VlcEntry { sym: 10, bits: 4 }, VlcEntry { sym: 10, bits: 4 }, VlcEntry { sym: 10, bits: 4 }, VlcEntry { sym: 10, bits: 4 }, VlcEntry { sym: 10, bits: 4 },
    VlcEntry { sym: 10, bits: 4 }, VlcEntry { sym: 10, bits: 4 }, VlcEntry { sym: 10, bits: 4 }, VlcEntry { sym: 10, bits: 4 }, VlcEntry { sym: 10, bits: 4 }, VlcEntry { sym: 10, bits: 4 }, VlcEntry { sym: 10, bits: 4 }, VlcEntry { sym: 10, bits: 4 },
    VlcEntry { sym: 10, bits: 4 }, VlcEntry { sym: 10, bits: 4 }, VlcEntry { sym: 10, bits: 4 }, VlcEntry { sym: 10, bits: 4 }, VlcEntry { sym: 10, bits: 4 }, VlcEntry { sym: 10, bits: 4 }, VlcEntry { sym: 10, bits: 4 }, VlcEntry { sym: 10, bits: 4 },
    VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 },
    VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 },
    VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 },
    VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 },
    VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 },
    VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 },
    VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 },
    VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 }, VlcEntry { sym: 9, bits: 3 },
    VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 },
    VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 },
    VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 },
    VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 },
    VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 },
    VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 },
    VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 },
    VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 },
    VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 },
    VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 },
    VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 },
    VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 },
    VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 },
    VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 },
    VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 },
    VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 }, VlcEntry { sym: 7, bits: 2 },
    VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 },
    VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 },
    VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 },
    VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 },
    VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 },
    VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 },
    VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 },
    VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 },
    VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 },
    VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 },
    VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 },
    VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 },
    VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 },
    VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 },
    VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 },
    VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 }, VlcEntry { sym: 8, bits: 2 },
];

pub const HUFF_LUT_2: [VlcEntry; 512] = [
    VlcEntry { sym: 0, bits: 0 }, VlcEntry { sym: 0, bits: 9 }, VlcEntry { sym: 1, bits: 8 }, VlcEntry { sym: 1, bits: 8 }, VlcEntry { sym: 2, bits: 7 }, VlcEntry { sym: 2, bits: 7 }, VlcEntry { sym: 2, bits: 7 }, VlcEntry { sym: 2, bits: 7 },
    VlcEntry { sym: 3, bits: 6 }, VlcEntry { sym: 3, bits: 6 }, VlcEntry { sym: 3, bits: 6 }, VlcEntry { sym: 3, bits: 6 }, VlcEntry { sym: 3, bits: 6 }, VlcEntry { sym: 3, bits: 6 }, VlcEntry { sym: 3, bits: 6 }, VlcEntry { sym: 3, bits: 6 },
    VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 },
    VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 }, VlcEntry { sym: 4, bits: 5 },
    VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 },
    VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 },
    VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 },
    VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 }, VlcEntry { sym: 5, bits: 4 },
    VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 },
    VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 },
    VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 },
    VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 },
    VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 },
    VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 },
    VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 },
    VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 }, VlcEntry { sym: 6, bits: 3 },
    VlcEntry { sym: 0, bits: 0 }, VlcEntry { sym: 14, bits: 9 }, VlcEntry { sym: 13, bits: 8 }, VlcEntry { sym: 13, bits: 8 }, VlcEntry { sym: 12, bits: 7 }, VlcEntry { sym: 12, bits: 7 }, VlcEntry { sym: 12, bits: 7 }, VlcEntry { sym: 12, bits: 7 },
    VlcEntry { sym: 11, bits: 6 }, VlcEntry { sym: 11, bits: 6 }, VlcEntry { sym: 11, bits: 6 }, VlcEntry { sym: 11, bits: 6 }, VlcEntry { sym: 11, bits: 6 }, VlcEntry { sym: 11, bits: 6 }, VlcEntry { sym: 11, bits: 6 }, VlcEntry { sym: 11, bits: 6 },
    VlcEntry { sym: 10, bits: 5 }, VlcEntry { sym: 10, bits: 5 }, VlcEntry { sym: 10, bits: 5 }, VlcEntry { sym: 10, bits: 5 }, VlcEntry { sym: 10, bits: 5 }, VlcEntry { sym: 10, bits: 5 }, VlcEntry { sym: 10, bits: 5 }, VlcEntry { sym: 10, bits: 5 },
    VlcEntry { sym: 10, bits: 5 }, VlcEntry { sym: 10, bits: 5 }, VlcEntry { sym: 10, bits: 5 }, VlcEntry { sym: 10, bits: 5 }, VlcEntry { sym: 10, bits: 5 }, VlcEntry { sym: 10, bits: 5 }, VlcEntry { sym: 10, bits: 5 }, VlcEntry { sym: 10, bits: 5 },
    VlcEntry { sym: 9, bits: 4 }, VlcEntry { sym: 9, bits: 4 }, VlcEntry { sym: 9, bits: 4 }, VlcEntry { sym: 9, bits: 4 }, VlcEntry { sym: 9, bits: 4 }, VlcEntry { sym: 9, bits: 4 }, VlcEntry { sym: 9, bits: 4 }, VlcEntry { sym: 9, bits: 4 },
    VlcEntry { sym: 9, bits: 4 }, VlcEntry { sym: 9, bits: 4 }, VlcEntry { sym: 9, bits: 4 }, VlcEntry { sym: 9, bits: 4 }, VlcEntry { sym: 9, bits: 4 }, VlcEntry { sym: 9, bits: 4 }, VlcEntry { sym: 9, bits: 4 }, VlcEntry { sym: 9, bits: 4 },
    VlcEntry { sym: 9, bits: 4 }, VlcEntry { sym: 9, bits: 4 }, VlcEntry { sym: 9, bits: 4 }, VlcEntry { sym: 9, bits: 4 }, VlcEntry { sym: 9, bits: 4 }, VlcEntry { sym: 9, bits: 4 }, VlcEntry { sym: 9, bits: 4 }, VlcEntry { sym: 9, bits: 4 },
    VlcEntry { sym: 9, bits: 4 }, VlcEntry { sym: 9, bits: 4 }, VlcEntry { sym: 9, bits: 4 }, VlcEntry { sym: 9, bits: 4 }, VlcEntry { sym: 9, bits: 4 }, VlcEntry { sym: 9, bits: 4 }, VlcEntry { sym: 9, bits: 4 }, VlcEntry { sym: 9, bits: 4 },
    VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 },
    VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 },
    VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 },
    VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 },
    VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 },
    VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 },
    VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 },
    VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 }, VlcEntry { sym: 8, bits: 3 },
    VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 },
    VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 },
    VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 },
    VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 },
    VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 },
    VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 },
    VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 },
    VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 },
    VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 },
    VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 },
    VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 },
    VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 },
    VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 },
    VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 },
    VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 },
    VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 },
    VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 },
    VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 },
    VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 },
    VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 },
    VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 },
    VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 },
    VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 },
    VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 },
    VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 },
    VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 },
    VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 },
    VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 },
    VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 },
    VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 },
    VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 },
    VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 }, VlcEntry { sym: 7, bits: 1 },
];

pub const HUFF_LUTS: [&[VlcEntry; 512]; 3] = [&HUFF_LUT_0, &HUFF_LUT_1, &HUFF_LUT_2];

pub const NOISE_TABLE: [i8; 256] = [
      30,   51,   22,   54,    3,    7,   -4,   38,   14,   55,   46,   81,   22,   58,   -3,    2,
      52,   31,   -7,   51,   15,   44,   74,   30,   85,  -17,   10,   33,   18,   80,   28,   62,
      10,   32,   23,   69,   72,   26,   35,   17,   73,   60,    8,   56,    2,    6,   -2,   -5,
      51,    4,   11,   50,   66,   76,   21,   44,   33,   47,    1,   26,   64,   48,   57,   40,
      38,   16,  -10,  -28,   92,   22,  -18,   29,  -10,    5,  -13,   49,   19,   24,   70,   34,
      61,   48,   30,   14,   -6,   25,   58,   33,   42,   60,   67,   17,   54,   17,   22,   30,
      67,   44,   -9,   50,  -11,   43,   40,   32,   59,   82,   13,   49,  -14,   55,   60,   36,
      48,   49,   31,   47,   15,   12,    4,   65,    1,   23,   29,   39,   45,   -2,   84,   69,
       0,   72,   37,   57,   27,   41,  -15,  -16,   35,   31,   14,   61,   24,    0,   27,   24,
      16,   41,   55,   34,   53,    9,   56,   12,   25,   29,   53,    5,   20,  -20,   -8,   20,
      13,   28,   -3,   78,   38,   16,   11,   62,   46,   29,   21,   24,   46,   65,   43,  -23,
      89,   18,   74,   21,   38,  -12,   19,   12,  -19,    8,   15,   33,    4,   57,    9,   -8,
      36,   35,   26,   28,    7,   83,   63,   79,   75,   11,    3,   87,   37,   47,   34,   40,
      39,   19,   20,   42,   27,   34,   39,   77,   13,   42,   59,   64,   45,   -1,   32,   37,
      45,   -5,   53,   -6,    7,   36,   50,   23,    6,   32,    9,  -21,   18,   71,   27,   52,
     -25,   31,   35,   42,   -1,   68,   63,   52,   26,   43,   66,   37,   41,   25,   40,   70,
];

pub const MLP_QUANTS: [u8; 16] = [
    16, 20, 24, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
];

pub const MLP_CHANNELS: [u8; 32] = [
    1, 2, 3, 4, 3, 4, 5, 3, 4, 5, 4, 5, 6, 4, 5, 4,
    5, 6, 5, 5, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
];

pub const MLP_LAYOUT: [u64; 32] = [
    0x4, 0x3, 0x103, 0x33,
    0xb, 0x10b, 0x3b, 0x7,
    0x107, 0x37, 0xf, 0x10f,
    0x3f, 0x107, 0x37, 0xf,
    0x10f, 0x3f, 0x3b, 0x37,
    0x3f, 0x0, 0x0, 0x0,
    0x0, 0x0, 0x0, 0x0,
    0x0, 0x0, 0x0, 0x0,
];

pub const THD_CHANCOUNT: [u8; 13] = [
    2, 1, 1, 2, 2, 2, 2, 1, 1, 2, 2, 1, 1,
];

pub const THD_LAYOUT: [u64; 13] = [
    0x3, 0x4, 0x8, 0x600,
    0x5000, 0xc0, 0x30, 0x100,
    0x800, 0x600000000, 0x180000000, 0x2000,
    0x800000000,
];

pub const THD_CHANNEL_ORDER: [u8; 20] = [
    0, 1, 2, 3, 9, 10, 12, 14, 6, 7, 4, 5, 8, 11, 33, 34, 31, 32, 13, 35,
];
