[package]
name = "codec-ra"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "LGPL-2.1-or-later"
description = "RealAudio decoders: ra_144, ra_288, ralf"

[dependencies]
oxideav-core.workspace = true

[dev-dependencies]
refcheck.workspace = true
demux-rm = { path = "../demux-rm" }
