[package]
name = "codec-wmv"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "LGPL-2.1-or-later"
repository.workspace = true
publish.workspace = true

[dependencies]
oxideav-core.workspace = true

[dev-dependencies]
refcheck.workspace = true
demux-asf = { path = "../demux-asf" }
oxideav-avi.workspace = true
